/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/action/addButton.vue')['default']
    AllButton: typeof import('./src/components/action/allButton.vue')['default']
    AppDate: typeof import('./src/components/common/AppDate.vue')['default']
    AppError: typeof import('./src/components/error/AppError.vue')['default']
    AppErrorDev: typeof import('./src/components/error/AppErrorDev.vue')['default']
    AppErrorProd: typeof import('./src/components/error/AppErrorProd.vue')['default']
    AppFooter: typeof import('./src/components/partials/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/partials/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/partials/AppSidebar.vue')['default']
    AuthLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    Badge: typeof import('./src/components/ui/isActiveBadge.vue')['default']
    Bootstrap5Pagination: typeof import('laravel-vue-pagination')['default']
    Cell: typeof import('./src/components/ui/cell.vue')['default']
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    FormSkeleton: typeof import('./src/components/ui/formSkeleton.vue')['default']
    GuestLayout: typeof import('./src/components/layouts/GuestLayout.vue')['default']
    IsActiveBadge: typeof import('./src/components/ui/isActiveBadge.vue')['default']
    JournalSkeleton: typeof import('./src/components/ui/tableSkeleton.vue')['default']
    LoadingPageTitle: typeof import('./src/components/ui/loadingPageTitle.vue')['default']
    NoRecordFound: typeof import('./src/components/ui/noRecordFound.vue')['default']
    NotFound: typeof import('./src/components/ui/noRecordFound.vue')['default']
    PageError: typeof import('./src/components/error/pageError.vue')['default']
    PageTitle: typeof import('./src/components/ui/pageTitle.vue')['default']
    PersistentToastContainer: typeof import('./src/components/ui/persistentToastContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/ui/searchInput.vue')['default']
    SingleFileUploader: typeof import('./src/components/SingleFileUploader.vue')['default']
    TableHead: typeof import('./src/components/table/tableHead.vue')['default']
    TableHeader: typeof import('./src/components/table/tableHeader.vue')['default']
    TableHeaderCell: typeof import('./src/components/table/tableHeaderCell.vue')['default']
    TableSkeleton: typeof import('./src/components/ui/tableSkeleton.vue')['default']
    Uploader: typeof import('./src/components/Uploader.vue')['default']
  }
}
