/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/journals/': RouteRecordInfo<'/journals/', '/journals', Record<never, never>, Record<never, never>>,
    '/journals/[id]': RouteRecordInfo<'/journals/[id]', '/journals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/journals/form': RouteRecordInfo<'/journals/form', '/journals/form', Record<never, never>, Record<never, never>>,
    '/journals/journalSkeleton': RouteRecordInfo<'/journals/journalSkeleton', '/journals/journalSkeleton', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/manuscripts/': RouteRecordInfo<'/manuscripts/', '/manuscripts', Record<never, never>, Record<never, never>>,
    '/manuscripts/[id]': RouteRecordInfo<'/manuscripts/[id]', '/manuscripts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/manuscripts/form': RouteRecordInfo<'/manuscripts/form', '/manuscripts/form', Record<never, never>, Record<never, never>>,
    '/manuscripts/journalSkeleton': RouteRecordInfo<'/manuscripts/journalSkeleton', '/manuscripts/journalSkeleton', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]': RouteRecordInfo<'/users/[id]', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/form': RouteRecordInfo<'/users/form', '/users/form', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...catchAll].vue': {
      routes: '/[...catchAll]'
      views: never
    }
    'src/pages/journals/index.vue': {
      routes: '/journals/'
      views: never
    }
    'src/pages/journals/[id].vue': {
      routes: '/journals/[id]'
      views: never
    }
    'src/pages/journals/form.vue': {
      routes: '/journals/form'
      views: never
    }
    'src/pages/journals/journalSkeleton.vue': {
      routes: '/journals/journalSkeleton'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/manuscripts/index.vue': {
      routes: '/manuscripts/'
      views: never
    }
    'src/pages/manuscripts/[id].vue': {
      routes: '/manuscripts/[id]'
      views: never
    }
    'src/pages/manuscripts/form.vue': {
      routes: '/manuscripts/form'
      views: never
    }
    'src/pages/manuscripts/journalSkeleton.vue': {
      routes: '/manuscripts/journalSkeleton'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/user.vue': {
      routes: '/user'
      views: never
    }
    'src/pages/users/index.vue': {
      routes: '/users/'
      views: never
    }
    'src/pages/users/[id].vue': {
      routes: '/users/[id]'
      views: never
    }
    'src/pages/users/form.vue': {
      routes: '/users/form'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
